Freaking Math Documentation: TimerBarControl Class Reference
TimerBarControl Class Reference
Public Member Functions
void Reset ()
void Pause ()
Private Member Functions
void Start ()
void Update ()
void RemoveLifeAndResetTimer ()
Private Attributes
float durationPerQuestion = 10.0f
Image imageTimerBar
LifeControl lifeControl
GameControl gameControl
bool isTimeOut = false
float timeCounter
Detailed Description
Definition at line 6 of file TimerBarControl.cs.
Member Function Documentation
Pause()
void TimerBarControl.Pause () inline
Definition at line 63 of file TimerBarControl.cs.
References isTimeOut.
RemoveLifeAndResetTimer()
void TimerBarControl.RemoveLifeAndResetTimer () inline private
Definition at line 68 of file TimerBarControl.cs.
References gameControl, lifeControl, and Reset().
Reset()
void TimerBarControl.Reset () inline
Definition at line 56 of file TimerBarControl.cs.
References durationPerQuestion, isTimeOut, and timeCounter.
Start()
void TimerBarControl.Start () inline private
Definition at line 17 of file TimerBarControl.cs.
References Reset().
Update()
void TimerBarControl.Update () inline private
Definition at line 23 of file TimerBarControl.cs.
References durationPerQuestion, isTimeOut, RemoveLifeAndResetTimer(), and timeCounter.
Member Data Documentation
durationPerQuestion
float TimerBarControl.durationPerQuestion = 10.0f private
Definition at line 8 of file TimerBarControl.cs.
gameControl
GameControl TimerBarControl.gameControl private
Definition at line 11 of file TimerBarControl.cs.
imageTimerBar
Image TimerBarControl.imageTimerBar private
Definition at line 9 of file TimerBarControl.cs.
isTimeOut
bool TimerBarControl.isTimeOut = false private
Definition at line 13 of file TimerBarControl.cs.
lifeControl
LifeControl TimerBarControl.lifeControl private
Definition at line 10 of file TimerBarControl.cs.
timeCounter
float TimerBarControl.timeCounter private
Definition at line 15 of file TimerBarControl.cs.
The documentation for this class was generated from the following file:
/Users/cheabora/WorkSpace/GameDev/FreakingMath/Assets/Scripts/TimerBarControl.cs