Freaking Math Documentation: GameControl Class Reference
GameControl Class Reference
Public Member Functions
void GiveAnswer ()
void HandleClick (int index)
void ResetBonusLife ()
void ShowGameOver ()
Private Member Functions
void Start ()
void GenerateQuestion ()
Private Attributes
GameObject[] hands
Text textScore
Text textQuestion
BrainScript brainScript
LifeControl lifeControl
Text textAnswer1
Text textAnswer2
Text textAnswer3
Text textAnswer4
GameOverControl gameOverControl
TimerBarControl timerBarControl
Image imageBonusLife
GameDataManager gameDataManager
int correctResult = -1
int score = 0
int countCorrect = 0
Detailed Description
Definition at line 6 of file GameControl.cs.
Member Function Documentation
GenerateQuestion()
void GameControl.GenerateQuestion () inline private
Definition at line 40 of file GameControl.cs.
References brainScript, correctResult, BrainScript.GenerateQuiz(), BrainScript.GetCorrectResult(), BrainScript.GetQuestion(), and BrainScript.GetResults().
GiveAnswer()
void GameControl.GiveAnswer () inline
Definition at line 61 of file GameControl.cs.
References brainScript, HandleClick(), and hands.
HandleClick()
void GameControl.HandleClick (int index) inline
Definition at line 68 of file GameControl.cs.
References brainScript, correctResult, countCorrect, GenerateQuestion(), lifeControl, score, ShowGameOver(), and timerBarControl.
ResetBonusLife()
void GameControl.ResetBonusLife () inline
Definition at line 117 of file GameControl.cs.
References countCorrect.
ShowGameOver()
void GameControl.ShowGameOver () inline
Definition at line 123 of file GameControl.cs.
References gameDataManager, gameOverControl, and score.
Start()
void GameControl.Start () inline private
Definition at line 32 of file GameControl.cs.
References GameDataManager.dataManager, gameDataManager, and GenerateQuestion().
Member Data Documentation
brainScript
BrainScript GameControl.brainScript private
Definition at line 12 of file GameControl.cs.
correctResult
int GameControl.correctResult = -1 private
Definition at line 27 of file GameControl.cs.
countCorrect
int GameControl.countCorrect = 0 private
Definition at line 30 of file GameControl.cs.
gameDataManager
GameDataManager GameControl.gameDataManager private
Definition at line 24 of file GameControl.cs.
gameOverControl
GameOverControl GameControl.gameOverControl private
Definition at line 20 of file GameControl.cs.
hands
GameObject [] GameControl.hands private
Definition at line 8 of file GameControl.cs.
imageBonusLife
Image GameControl.imageBonusLife private
Definition at line 22 of file GameControl.cs.
lifeControl
LifeControl GameControl.lifeControl private
Definition at line 13 of file GameControl.cs.
score
int GameControl.score = 0 private
Definition at line 28 of file GameControl.cs.
textAnswer1
Text GameControl.textAnswer1 private
Definition at line 15 of file GameControl.cs.
textAnswer2
Text GameControl.textAnswer2 private
Definition at line 16 of file GameControl.cs.
textAnswer3
Text GameControl.textAnswer3 private
Definition at line 17 of file GameControl.cs.
textAnswer4
Text GameControl.textAnswer4 private
Definition at line 18 of file GameControl.cs.
textQuestion
Text GameControl.textQuestion private
Definition at line 11 of file GameControl.cs.
textScore
Text GameControl.textScore private
Definition at line 10 of file GameControl.cs.
timerBarControl
TimerBarControl GameControl.timerBarControl private
Definition at line 21 of file GameControl.cs.
The documentation for this class was generated from the following file:
/Users/cheabora/WorkSpace/GameDev/FreakingMath/Assets/Scripts/GameControl.cs