Freaking Math Documentation: LifeControl Class Reference
LifeControl Class Reference
Public Member Functions
void RemoveLife ()
void AddLife ()
bool StillHasLife ()
bool IsDie ()
void ResetLife ()
Private Member Functions
void Start ()
IEnumerator _addLife ()
void RefreshExtraLife ()
Private Attributes
Toggle[] toggles
int totalLife = 5
Text textExtraLife
Animator animator
Detailed Description
Definition at line 6 of file LifeControl.cs.
Member Function Documentation
_addLife()
IEnumerator LifeControl._addLife () inline private
Definition at line 47 of file LifeControl.cs.
References animator, RefreshExtraLife(), toggles, and totalLife.
AddLife()
void LifeControl.AddLife () inline
Definition at line 42 of file LifeControl.cs.
References _addLife().
IsDie()
bool LifeControl.IsDie () inline
Definition at line 115 of file LifeControl.cs.
References totalLife.
RefreshExtraLife()
void LifeControl.RefreshExtraLife () inline private
Definition at line 97 of file LifeControl.cs.
References totalLife.
RemoveLife()
void LifeControl.RemoveLife () inline
Definition at line 25 of file LifeControl.cs.
References RefreshExtraLife(), toggles, and totalLife.
ResetLife()
void LifeControl.ResetLife () inline
Definition at line 120 of file LifeControl.cs.
References toggles, and totalLife.
Start()
void LifeControl.Start () inline private
Definition at line 15 of file LifeControl.cs.
References toggles.
StillHasLife()
bool LifeControl.StillHasLife () inline
Definition at line 110 of file LifeControl.cs.
References totalLife.
Member Data Documentation
animator
Animator LifeControl.animator private
Definition at line 13 of file LifeControl.cs.
textExtraLife
Text LifeControl.textExtraLife private
Definition at line 11 of file LifeControl.cs.
toggles
Toggle [] LifeControl.toggles private
Definition at line 8 of file LifeControl.cs.
totalLife
int LifeControl.totalLife = 5 private
Definition at line 9 of file LifeControl.cs.
The documentation for this class was generated from the following file:
/Users/cheabora/WorkSpace/GameDev/FreakingMath/Assets/Scripts/LifeControl.cs